### ISSUE TITLE
Feil på summen av "Foreldrepenger dere har igjen"

### ISSUE THREAD

**Issue by jostyposty** [navikt/foreldrepengesoknad#2903]
Vi har mista 14 dager pga sen registrering i A-registeret. Surt, men greit. Jeg trodde vi var på 0 dager igjen av felles, og det bekrefter også NAV på telefon til meg i dag. Det står 0 dager hos henne.

Det som jeg stusser på er at hos oss står det 2 uker og 4 dager. Det er 14 dager, altså samme antall dager som vi har mista.

Jeg stusser også over at vi tilsynelatende får lov til å gjøre endringer de stedene der det står "uten registrert periode eller utsettelse". Det sier nemlig NAV på telefon at ikke skal gå an bak i tid.

Er det noe rart her?

![2021-09-09-kanskje-feil](https://user-images.githubusercontent.com/429242/132694601-321e8ed5-55c2-432e-851b-4b8b1654e282.PNG)

Uansett, superbra skjema!

**Comment by AndreasDybdahl** [comment]
Hei hei, @jostyposty. Det er ikke noe feil her, det ser bare veldig rart ut. Det som skjer her er at du har fått avslag på 14 dager som en følge av saksbehandling, sannsynligvis pågrunn av noe problemer med AAReg som du skriver. 

Når du så kommer inn i søknaden blir disse avslåtte dagene skrotet og markert som hull i din plan for foreldrepenger. Videre vil den oversikten på bunnen av siden regne seg frem til at du har 14 dager til overs, som er korrekt det.

Spørsmålet blir da hvorfor blir ikke disse manglende dagene markert på en annen måte som gjør at det blir litt satt i stein at du ikke kan sette inn noe der? Svaret er: it's complicated :sweat_smile:

Vi skal ikke stoppe bruker fra å gjøre ting de har lov til og du har fortsatt lov til å søke om å ta fellesperioden her, selv om du kommer til å få den avslått igjen av samme grunn som sist. Det finnes også x antall unntak hvor du kanskje har lov til å søke om disse dagene allikevel, så det hadde vært dumt om vi sperret folk fra å gjøre det. Hovedproblemet er at foreldrepengesøknaden måtte ha visst utfallet av en saksbehandling for å være korrekt i når det skal og ikke skal være mulig å fylle inn disse dagene.

Må innrømme at dette er ikke akkurat 100% god UX og vi kan kanskje finne en lurere løsning på dette i fremtiden en gang, men dette er faktisk working as intended i skrivende stund :)

Håper dette har gitt litt god info på hvorfor ting fungerer som det gjør!
